[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science", "no-std", "embedded", "wasm"]
description = "Flexible and Comprehensive Deep Learning Framework in Rust"
documentation = "https://docs.rs/burn"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
license.workspace = true
name = "burn"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn"
rust-version = "1.82"
version.workspace = true

[features]
default = ["burn-core/default", "burn-train?/default", "std"]
doc = ["default", "train", "burn-core/doc", "burn-train/doc"]
std = ["burn-core/std"]

# Training with full features
train = ["burn-train", "autodiff", "dataset"]

## Includes the Text UI (progress bars, metric plots)
tui = ["burn-train?/tui"]

##  Includes system info metrics (CPU/GPU usage, etc)
metrics = ["burn-train?/metrics"]

browser = ["burn-core/browser"]

# Datasets
dataset = ["burn-core/dataset"]

sqlite = ["burn-core/sqlite"]
sqlite-bundled = ["burn-core/sqlite-bundled"]

audio = ["burn-core/audio"]
vision = ["burn-core/vision"]

# Backends
autodiff = ["burn-core/autodiff"]
fusion = ["burn-core/fusion"]

## Backend features
accelerate = ["burn-core/accelerate"]
autotune = ["burn-core/autotune"]
blas-netlib = ["burn-core/blas-netlib"]
candle-cuda = ["burn-core/candle-cuda"]
metal = ["burn-core/metal"]
openblas = ["burn-core/openblas"]
openblas-system = ["burn-core/openblas-system"]
template = ["burn-core/template"]

candle = ["burn-core/candle"]
cuda-jit = ["burn-core/cuda-jit"]
hip-jit = ["burn-core/hip-jit"]
ndarray = ["burn-core/ndarray"]
remote = ["burn-core/remote"]
router = ["burn-core/router"]
server = ["burn-core/server"]
tch = ["burn-core/tch"]
wgpu = ["burn-core/wgpu"]
wgpu-spirv = ["burn-core/wgpu-spirv"]

# Network utils
network = ["burn-core/network"]

# Experimental
experimental-named-tensor = ["burn-core/experimental-named-tensor"]

# Records
record-backward-compat = ["burn-core/record-backward-compat"]
record-item-custom-serde = ["burn-core/record-item-custom-serde"]

[dependencies]

# ** Please make sure all dependencies support no_std when std is disabled **

burn-core = { path = "../burn-core", version = "0.16.0", default-features = false }
burn-train = { path = "../burn-train", version = "0.16.0", optional = true, default-features = false }
